---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules
    - core/client/node_modules
    - core/client/bower_components

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - cd ember
  - npm install
  - bower install

script:
  - npm test
  - ember build -o ../public
  - cd ..
  - npm test
